// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yarhxdtvsnketiagqrpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhcmh4ZHR2c25rZXRpYWdxcnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzA1MTMsImV4cCI6MjA2MzE0NjUxM30.izKhR4PNLt5GiHG_rxKv9RVfJITC7sKO8XfBxgqdow8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);